dist: xenial

sudo: required

language: generic

services:
- docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
- docker info

jobs:
  include:
    - stage: build, test, deploy
      env:
      - PROCESS=7.7/alpine
      script: tools/build_test_push.sh 7.7/alpine
